MODEL_TYPE=adverb_transform
DATA_DIRECTORY=modular_150_extra_full
SEEDS=$1
MODE=$2
SIMPLIFIED_ARCHITECTURE=no
USE_ATTENTION=yes
USE_CONDITIONAL_ATTENTION=no
TYPE_ATTENTION=luong
ATTENTION_KEY=adverb_input_tensor
CONDITIONAL_ATTENTION_KEY=none
UPSAMPLE_ISOLATED=100
WEIGHT_DECAY=1e-5
MODULAR=yes
COLLAPSE_ALO=yes
K=5
MODEL_SIZE=big
ISOLATE_ADVERB_TYPES=""
ONLY_KEEP_ADVERBS=""

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "SEEDS: ${1}"
    echo "MODE: ${2}"
    echo Invalid Arguments
    exit 1
fi

./start_experiments.sh $DATA_DIRECTORY $SEEDS $MODE $MODEL_TYPE $SIMPLIFIED_ARCHITECTURE $USE_ATTENTION $USE_CONDITIONAL_ATTENTION $TYPE_ATTENTION $ATTENTION_KEY $CONDITIONAL_ATTENTION_KEY ${UPSAMPLE_ISOLATED} ${WEIGHT_DECAY} ${COLLAPSE_ALO} ${MODULAR} ${K} ${MODEL_SIZE} ${ISOLATE_ADVERB_TYPES} ${ONLY_KEEP_ADVERBS}
