MODEL_TYPE=full
DATA_DIRECTORY=compositional_splits
SEEDS=$1
MODE=error_analysis
SIMPLIFIED_ARCHITECTURE=no
USE_ATTENTION=yes
USE_CONDITIONAL_ATTENTION=no
TYPE_ATTENTION=bahdanau
ATTENTION_KEY=input_tensor
CONDITIONAL_ATTENTION_KEY=None
UPSAMPLE_ISOLATED=100
WEIGHT_DECAY=1e-5
COLLAPSE_ALO=yes
MODULAR=no
K=5
MODEL_SIZE=big

if [ -z "$1" ]; then
    echo "SEEDS: ${1}"
    echo Invalid Arguments
    exit 1
fi

./start_experiments.sh $DATA_DIRECTORY $SEEDS $MODE $MODEL_TYPE $SIMPLIFIED_ARCHITECTURE $USE_ATTENTION $USE_CONDITIONAL_ATTENTION $TYPE_ATTENTION $ATTENTION_KEY $CONDITIONAL_ATTENTION_KEY ${UPSAMPLE_ISOLATED} ${WEIGHT_DECAY} ${COLLAPSE_ALO} ${MODULAR} ${K} ${MODEL_SIZE}